apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/use-regex : 'true'
spec:
  rules:
    - host: http://34.118.121.220/
      http:
        paths:
          - path: /login
            backend:
              serviceName: auth-clusterip-srv
              servicePort: 4000
          - path: /signup
            backend:
              serviceName: auth-clusterip-srv
              servicePort: 4000 
          - path: /create_question
            backend:
              serviceName: questions-clusterip-srv
              servicePort: 4001
          - path: /edit_question
            backend:
              serviceName: questions-clusterip-srv
              servicePort: 4001
          - path: /edit_answer
            backend:
              serviceName: answer-clusterip-srv
              servicePort: 4002  
          - path: /create_answer
            backend:
              serviceName: answer-clusterip-srv
              servicePort: 4002
          - path: /profile/(*)?
            backend:
              serviceName: query-clusterip-srv
              servicePort: 4003
          - path: /statistics
            backend:
              serviceName: query-clusterip-srv
              servicePort: 4003 
          - path: /question_view/(*)?
            backend:
              serviceName: query-clusterip-srv
              servicePort: 4003 
          - path: /home
            backend:
              serviceName: query-clusterip-srv
              servicePort: 4003                   
          - path: /
            backend:
              serviceName: client-clusterip-srv
              servicePort: 3000
              